/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:e877b3a7-7803-4b86-b71c-6ce82e0f98ca",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_UC0q9PWNp",
    "aws_user_pools_web_client_id": "2rvkcldh8c5hi2u0a7cl6c5i3q",
    "oauth": {}
};

export default awsmobile;
